server:
  port: 0

spring:
  application:
    name: config-server
  profiles:
    active: native
  output:
    ansi:
      enabled: always
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:config/telemetry/{application}
            - classpath:config/commerce/{application}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/