version: '3.8'

services:
  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9101:9101"
    restart: unless-stopped
    environment:
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    networks:
      - kafka-net

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    networks:
      - kafka-net
    command: >
      bash -c '
        kafka-topics --create --topic telemetry.sensors.v1 --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092 &&
        kafka-topics --create --topic telemetry.snapshots.v1 --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092 &&
        kafka-topics --create --topic telemetry.hubs.v1 --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092
      '
    init: true

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    networks:
      - kafka-net
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - kafka

  db:
    image: postgres:16.1
    container_name: postgres-analyzer
    environment:
      POSTGRES_USER: analyzer
      POSTGRES_PASSWORD: analyzer
      POSTGRES_DB: analyzer
    ports:
      - "6541:5432"
    volumes:
      - pgdata_analyzer:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - kafka-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      timeout: 5s
      interval: 5s
      retries: 10

  db2:
    image: postgres:16.1
    container_name: postgres-cart
    environment:
      POSTGRES_USER: cart
      POSTGRES_PASSWORD: cart
      POSTGRES_DB: cart
    ports:
      - "6542:5432"
    volumes:
      - pgdata_cart:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - kafka-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      timeout: 5s
      interval: 5s
      retries: 10

  db3:
    image: postgres:16.1
    container_name: postgres-store
    environment:
      POSTGRES_USER: store
      POSTGRES_PASSWORD: store
      POSTGRES_DB: store
    ports:
      - "6543:5432"
    volumes:
      - pgdata_store:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - kafka-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      timeout: 5s
      interval: 5s
      retries: 10

  db4:
    image: postgres:16.1
    container_name: postgres-warehouse
    environment:
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
      POSTGRES_DB: warehouse
    ports:
      - "6544:5432"
    volumes:
      - pgdata_warehouse:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - kafka-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      timeout: 5s
      interval: 5s
      retries: 10

networks:
  kafka-net:
    name: kafka-net
    driver: bridge

volumes:
  pgdata_analyzer:
  pgdata_cart:
  pgdata_store:
  pgdata_warehouse: