spring:
  application:
    name: collector

grpc:
  server:
    port: 59091
    netty:
      use-epoll:

collector:
  kafka:
    producer:
      properties:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: ru.practicum.kafka.serializer.GeneralAvroSerializer
        client.id: telemetry.collection
      topics:
        sensors-events: telemetry.sensors.v1
        hubs-events: telemetry.hubs.v1

logging:
  level:
    ru:
      yandex:
        practicum:
          telemetry: TRACE
      practicum:
        kafka: INFO
    org:
      springframework: ERROR
    apache:
      kafka: WARN
    io.grpc.netty: DEBUG
    io.netty: DEBUG
